<div class = "container">
    <div class = "d-flex justify-content-center mt-5">
        <div 
            class = "card"
            style = "width: 36rem;"
        >
            <div class = "card-body">
                
                <div class = "d-flex justify-content-center">
                    <img src = "/assets/images/twitter_logo.png">
                </div>

                <div class="row">
                    <div class="col">
                        <h2>Crie sua conta</h2>
                    </div>
                </div>

                <div class = "row">

                    <div class = "col">

                        <form 
                            action = "/registrar"
                            method = "post"
                        >
                            <div class = "mb-3">
                                <input 
                                    type = "text"
                                    name = "nome" 
                                    class = "form-control"
                                    placeholder = "Nome"
                                    value = "<?= $this -> view -> usuario ['nome']?>"
                                >
                            </div>

                            <div class = "mb-3">
                                <input 
                                    type = "email"
                                    name = "email" 
                                    class = "form-control"
                                    placeholder = "E-mail"
                                    value = "<?= $this -> view -> usuario ['email']?>"
                                >
                            </div>

                            <div class = "mb-3">
                                <input 
                                    type = "password"
                                    name = "senha"
                                    class = "form-control"
                                    placeholder = "Senha"
                                    value = "<?= $this -> view -> usuario ['senha']?>"
                                >
                            </div>

                            <div class = "mt-4 mb-4">
                                <small class ="form-text">
                                    Ao inscrever-se, você concorda com os Termos de Serviço e com as Políticas de Privacidade, 
                                    incluindo o Uso de Cookies. Outras pessoas poderão encontrar você pelo e-mail ou número de telefone fornecido 
                                    · Opções de Privacidade
                                </small>
                            </div>

                            <div class = "d-grid gap-2">
                                <button
                                    type = "submit" 
                                    class = "btn btn-primary btn-block"
                                >
                                    Inscrever-se
                                </button>
                            </div>

                            <?php if ($this -> view -> erroCadastro) {?>
                            
                                <div class = "mt-4">
                                    <small class = "form-text text-danger">
                                        Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente
                                    </small>
                                </div>

                            <?php }?>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>