<nav class = "navbar navbar-expand-lg menu">
	<div class = "container">
	  <div class = "navbar-nav">
            <a 
                class = "menuItem" 
                href = "/timeline"
            >
                Home
            </a>

            <a 
                class = "menuItem" 
                href = "/sair"
            >
                Sair
            </a>

			<img 
                src = "/assets/images/twitter_logo.png" 
                class = "menuIco"
            >
	  </div>
	</div>
</nav>

<div class = "container mt-5">
	<div class = "row pt-2">
		
		<div class = "col-md-3">

			<div class = "perfil">
				<div class = "perfilTopo">

				</div>

				<div class = "perfilPainel">	

					<div class = "row mt-2 mb-2">
						<div class = "col mb-2">
							<span class = "perfilPainelNome"> <?= $this -> view -> infoUsuario ['nome'] ?> </span>
						</div>
					</div>

					<div class = "row mb-2">

						<div class = "col">
							<span class = "perfilPainelItem">Tweets</span> <br>
							<span class = "perfilPainelItemValor"> <?= $this -> view -> totalTweets ['totalTweets']?> </span>
						</div>

						<div class = "col">
							<span class = "perfilPainelItem">Seguindo</span> <br>
							<span class = "perfilPainelItemValor"> <?= $this -> view -> totalASeguir ['totalASeguir']?> </span>
						</div>

						<div class = "col">
							<span class = "perfilPainelItem">Seguidores</span> <br>
							<span class = "perfilPainelItemValor"> <?= $this -> view -> totalSeguidores ['totalSeguidores'] ?> </span>
						</div>

					</div>
				</div>
			</div>

		</div>

		<div class = "col-md-6">
			
			<div class = "row mb-2">
				<div class = "col">
					<div class = "card">
						<div class = "card-body">
							<form
                                action = "/quemSeguir"
                                method = "get"
                            >
								<div class = "input-group mb-3">

									<input 
                                        type = "text" 
                                        name = "pesquisar"
                                        class = "form-control" 
                                        placeholder = "Quem você está procurando?"
                                    >

                                    <button 
                                        type = "submit"
                                        class = "btn btn-primary" 
                                    >
                                        Procurar
                                    </button>

								</div>
							</form>
						</div>
					</div>
				</div>
			</div>

            <?php foreach ($this -> view -> usuarios as $indice => $usuario) { ?>
                <div class = "row mb-2">
                    <div class = "col">
                        <div class = "card">
                            <div class = "card-body">
                                <div class = "row">
                                    <div class = "col-md-6">
                                        <?= $usuario ['nome'] ?>
                                    </div>
                                
                                    <div class = "col-md-6 d-flex justify-content-end">
                                        <div>
                                            <?php if ($usuario ['seguindo_sn'] == 0) {?>
                                                <a 
                                                    href = "/acao?acao=seguir&idUsuario=<?=$usuario ['id']?>" 
                                                    class = "btn btn-primary"
                                                >
                                                    Seguir
                                                </a>
                                            <?php }   else { ?>
                                                <a 
                                                    href = "/acao?acao=deixar_de_seguir&idUsuario=<?=$usuario ['id']?>" 
                                                    class = "btn btn-danger"
                                                >
                                                    Deixar de seguir
                                                </a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>
		</div>
	</div>
</div>